{
 "title": "Solar Power",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cost_per_kwh", "label": "Cost Per kWh ($)", "query": "0.1456" },
   { "name": "timezone", "label": "Collector Timezone", "query": "America/Los_Angeles" }
  ]
 },
 "panels": [
  {
   "title": "Current Consumption",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(reading_time, '1m') AS time, w_now/1000 AS \"Consumed\"\nFROM public.consumption\nWHERE $__timeFilter(reading_time)"
    }
   ]
  },
  {
   "title": "Today's Production/Consumption Ratio",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  max(p.wh_today)/max(c.wh_today)*100 AS \"Ratio\"\nFROM (\n    SELECT date_trunc('minute', reading_time) AS time, *\n    FROM public.consumption\n    WHERE $__timeFilter(reading_time)\n) AS c\nJOIN (\n    SELECT date_trunc('minute', reading_time) AS time, *\n    FROM public.production\n    WHERE $__timeFilter(reading_time)\n) AS p ON c.time = p.time;"
    }
   ]
  },
  {
   "title": "Lifetime Production/Consumption Ratio",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  max(p.wh_lifetime)/max(c.wh_lifetime)*100 AS \"Ratio\"\nFROM (\n    SELECT date_trunc('minute', reading_time) AS time, *\n    FROM public.consumption\n    WHERE $__timeFilter(reading_time)\n) AS c\nJOIN (\n    SELECT date_trunc('minute', reading_time) AS time, *\n    FROM public.production\n    WHERE $__timeFilter(reading_time)\n) AS p ON c.time = p.time;"
    }
   ]
  },
  {
   "title": "Current Production",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(reading_time, '1m') AS time, w_now/1000 AS \"Produced\"\nFROM public.production\nWHERE $__timeFilter(reading_time)"
    }
   ]
  },
  {
   "title": "Lifetime Trees Saved",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "🌲" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(reading_time, '1m') AS time, (wh_lifetime/1000)/55.3\nFROM public.production\nWHERE $__timeFilter(reading_time)"
    }
   ]
  },
  {
   "title": "Consumed Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(reading_time, '1m') AS time, wh_today/1000 AS \"kWh Hours Today\"\nFROM public.consumption\nWHERE $__timeFilter(reading_time)"
    }
   ]
  },
  {
   "title": "Consumed Lifetime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(reading_time, '1m') AS time, wh_lifetime/1000 AS \"kWh Hours Lifetime\"\nFROM public.consumption\nWHERE $__timeFilter(reading_time)"
    }
   ]
  },
  {
   "title": "Produced Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(reading_time, '1m') AS time, wh_today/1000 AS \"kWh Hours Today\"\nFROM public.production\nWHERE $__timeFilter(reading_time)"
    }
   ]
  },
  {
   "title": "Produced Lifetime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(reading_time, '1m') AS time, wh_lifetime/1000 AS \"kWh Hours Lifetime\"\nFROM public.production\nWHERE $__timeFilter(reading_time)"
    }
   ]
  },
  {
   "title": "Today's Consumed Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(reading_time, '1m') AS time, (wh_today/1000)*${cost_per_kwh}\nFROM public.consumption\nWHERE $__timeFilter(reading_time)"
    }
   ]
  },
  {
   "title": "Lifetime Consumed Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(reading_time, '1m') AS time, (wh_lifetime/1000)*${cost_per_kwh}\nFROM public.consumption\nWHERE $__timeFilter(reading_time)"
    }
   ]
  },
  {
   "title": "Today's Produced Savings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(reading_time, '1m') AS time, (wh_today/1000)*${cost_per_kwh}\nFROM public.production\nWHERE $__timeFilter(reading_time)"
    }
   ]
  },
  {
   "title": "Lifetime Produced Savings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(reading_time, '1m') AS time, (wh_lifetime/1000)*${cost_per_kwh}\nFROM public.production\nWHERE $__timeFilter(reading_time)"
    }
   ]
  },
  {
   "title": "Energy Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(c.time, '1m') AS time,\n    p.w_now/1000 AS \"Produced\",\n    c.w_now/1000 AS \"Consumed\",\n    CASE\n        WHEN c.w_now > p.w_now THEN\n            (c.w_now-p.w_now)/1000\n        ELSE 0\n    END AS \"Imported\",\n    CASE\n        WHEN p.w_now > c.w_now THEN\n            (p.w_now-c.w_now)/1000\n        ELSE 0\n    END AS \"Exported\"\nFROM (\n    SELECT date_trunc('minute', reading_time) AS time, *\n    FROM public.consumption\n    WHERE $__timeFilter(reading_time)\n) AS c\nJOIN (\n    SELECT date_trunc('minute', reading_time) AS time, *\n    FROM public.production\n    WHERE $__timeFilter(reading_time)\n) AS p ON c.time = p.time\n"
    }
   ]
  },
  {
   "title": "Recent Consumption and Production",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n    date_trunc('day', c.time) AS \"Date\",\n    c.wh_today/1000 AS \"kWh Consumed\",\n    p.wh_today/1000 AS \"kWh Produced\",\n    p.wh_today/c.wh_today*100 AS \"Ratio\"\nFROM (\n    SELECT date_trunc('day', reading_time) AS time, wh_today\n    FROM public.consumption\n    WHERE reading_time AT TIME ZONE '${timezone}' IN (\n        SELECT max(x.reading_time)\n        FROM (\n            SELECT reading_time AT TIME ZONE '${timezone}' AS reading_time, wh_today\n            FROM public.consumption\n            WHERE $__timeFilter(reading_time)\n        ) x\n        GROUP BY date_trunc('day', x.reading_time)\n    )\n) c\nJOIN (\n    SELECT date_trunc('day', reading_time) AS time, wh_today\n    FROM public.production\n    WHERE reading_time AT TIME ZONE '${timezone}' IN (\n        SELECT max(x.reading_time)\n        FROM (\n            SELECT reading_time AT TIME ZONE '${timezone}' AS reading_time, wh_today\n            FROM public.production\n            WHERE $__timeFilter(reading_time)\n        ) x\n        GROUP BY date_trunc('day', x.reading_time)\n    )\n) p ON c.time = p.time\nORDER BY 1 DESC"
    }
   ]
  }
 ]
}